---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # monitoring / observability (LGTM)
  - ../../../apps/lgtm-prometheus/overlays/dev
  - ../../../apps/lgtm-loki/overlays/dev
  - ../../../apps/lgtm-alloy/overlays/dev
  - ../../../apps/lgtm-tempo/overlays/dev
