---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: traefik
spec:
  encryptedData:
    api-token: AgAsehCkYZeGGhDpRSMqnCgMCx0vxSoN5ZueFZNuaLP8RAjNPFc/97g0WVIWxOH8rAYCKef9musAxCWRvc2+fRTTP+42M/tIXLppWmObCN4ZTnPbBPidzEwQxp9aNFpbyg0+gBQOgP1n2ZsHJa15O9DefyvSnP+la6LoyZqZVBziE6IPokwKLOJGozAGmCmv4NJSJ1mIhTfv9XJL9D0duDicP2ocRl296Kmj+93Owj6ZdS7uifivW41mvwjh4pmeqFpGvrAlzjzRn7YVcToPCFMP2aY2TdgpVVe6iOrFVyqahw8B+BWoX3n16hGGcmIbjxCm5ixwCGJEENUaK5yd/Ni1KlBMXwOCNRUwtRYNNwWrkoHZ5NVpA5JZ7oRXTIfidFgpLF80d83GIoiXBik5LIyxmDOMZ2sobfLZ2zZMVB86hUyHr9d7yD7SmUziJHsS3anKOi4+V1/wPeDdmT9NEO0vl9SpDpCymoCh9g78v/NWT9zFVlc7am3GXxpPx8NFe+Mhk6HitKGOFhrbkn/lSZYPkxh+kvUeVoiLBmZuw9qsfv1VKOX2RMwg5d6nrkmSU1XV8qcpITWYE9ziUzZ81MhJ+8xMCUQOP6t1uLPtnqhopX1nWtcThvT91hTmMGMR8xGC3vTtur0Rdxh+Q7GtK0WZzaQl8cQe2VPsILnzzPCHf9iJW7imvXpNRtqElVkb7zAtQ8vL8BxDjmEsmeOJH0Lz9QtT1wo+GC/yhOINY1vwRY9f3stKtGEL
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: traefik
    type: Opaque
