---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden
  namespace: flux-system
spec:
  chart:
    spec:
      chart: self-host
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: bitwarden
        namespace: flux-system
      version: 2025.9.x
  interval: 1m0s
  timeout: 10m
  releaseName: bitwarden
  targetNamespace: bitwarden
  values:
    general:
      # Domain name for the service
      domain: "bitwarden.thelemonsclan.com"
      ingress:
        # Set to false if using a custom ingress
        enabled: false

      # Disable account registration on web vault
      disableUserRegistration: "false"
      # Comma-separated list of email addresses for Admin users
      admins: "lemonsml@outlook.com,goalkeeper171717@gmail.com"
      email:
        # Email address used for invitations, typically no-reply@smtp-host
        replyToEmail: "no-reply@thelemonsclan.com"
        # Your SMTP server hostname (recommended) or IP address
        smtpHost: "smtp.gmail.com"
        # The SMTP port used by the SMTP server
        smtpPort: "465"
        # Whether your SMTP server uses an encryption protocol, "true" for SSL, "false" for TLS
        smtpSsl: "true"

    # Specify the name of the shared storage class
    # This storage class requires ReadWriteMany.  You will need to provide your own storage class.  Storage classes with automatic volume previsioners are recommended.
    sharedStorageClassName: "longhorn"

    # Secrets are required.  Review the chart README on GitHub for details on creating these secrets
    secrets:
      secretName: bitwarden-secret

    # Data volume sizes for shared PVCs
    volume:
      dataprotection:
        # Use an existing PVC by specifying the name.
        existingClaim: bitwarden-self-host-dataprotection
        labels: {}
      attachments:
        # Use an existing PVC by specifying the name.
        existingClaim: bitwarden-self-host-attachments
        labels: {}
      licenses:
        # Use an existing PVC by specifying the name.
        existingClaim: bitwarden-self-host-licenses
        labels: {}
      logs:
        # Logs are disabled by default
        enabled: false
        # Use an existing PVC by specifying the name.
        existingClaim: bitwarden-self-host-logs
        labels: {}

    #
    # Configure database
    #
    database:

      # The MSSQL volumes for the PVCs
      volume:
        backups:
          # Use an existing PVC by specifying the name.
          existingClaim: bitwarden-self-host-mssqlbackups
        labels: {}
        data:
          # Use an existing PVC by specifying the name.
          existingClaim: bitwarden-self-host-mssqldata
        labels: {}
        log:
          # Use an existing PVC by specifying the name.
          existingClaim: bitwarden-self-host-mssqllog
        labels: {}
