apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: bitwarden-kustomization
  namespace: flux-system
resources:
- bitwarden_SealedSecret.yaml
- bitwarden_PVC.yaml
- bitwarden_HelmRepository.yaml
- bitwarden_HelmRelease.yaml
- bitwarden_Middleware_IngressRoute.yaml