apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitwarden_helm-repository.yaml
  - bitwarden_helmrelease.yaml
  - bitwarden_ingress.yaml
  - bitwarden_pvcs.yaml
  - bitwarden_sealedsecret.yaml
