apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jellyfin-kustomization
  namespace: flux-system
resources:
- jellyfin-namespace.yaml
- jellyfin-pvcs.yaml
# - jellyfin-helmsource.yaml
# - jellyfin-helmrelease.yaml
# - jellyfin-ingress.yaml