---
apiVersion: v1
kind: Namespace
metadata:
  name: bitwarden
  labels:
    name: bitwarden
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared-tunnel
  labels:
    name: cloudflared-tunnel
---
apiVersion: v1
kind: Namespace
metadata:
  name: ddb-proxy
  labels:
    name: ddb-proxy
---
apiVersion: v1
kind: Namespace
metadata:
  name: foundry-vtt-kf
  labels:
    name: foundry-vtt-kf
---
apiVersion: v1
kind: Namespace
metadata:
  name: foundry-vtt-mll
  labels:
    name: foundry-vtt-mll
---
apiVersion: v1
kind: Namespace
metadata:
  name: foundry-vtt-tjk
  labels:
    name: foundry-vtt-tjk
---
apiVersion: v1
kind: Namespace
metadata:
  name: foundry-vtt-tw
  labels:
    name: foundry-vtt-tw
---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
  labels:
    name: home-assistant
---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
  labels:
    name: jellyfin
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    name: longhorn-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlx-portfolio
  labels:
    name: mlx-portfolio
---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
  labels:
    name: pihole
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    name: traefik
