---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../namespaces

  # init
  - ../../../apps/sealed-secrets/overlays/prd

  # recovery
  - ../../../apps/longhorn/overlays/prd
  - ../../../apps/nvidia/overlays/prd
  - ../../../apps/traefik/overlays/prd
  # live
  - ../../../apps/bitwarden/overlays/prd
  - ../../../apps/cert-manager/overlays/prd
  - ../../../apps/cloudflared/overlays/prd
  - ../../../apps/ddb-proxy/overlays/prd
  - ../../../apps/foundry-vtt-kf/overlays/prd
  - ../../../apps/foundry-vtt-mll/overlays/prd
  - ../../../apps/foundry-vtt-tjk/overlays/prd
  - ../../../apps/foundry-vtt-tw/overlays/prd
  - ../../../apps/homne-assistant/overlays/prd
  - ../../../apps/jellyfin/overlays/prd
  - ../../../apps/mlx-portfolio/overlays/prd
  - ../../../apps/pihole/overlays/prd