---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # live
 # - ../../../apps/bitwarden/overlays/prd
  - ../../../apps/cert-manager/overlays/prd
  - ../../../apps/cloudflared/overlays/prd
  - ../../../apps/ddb-proxy/overlays/prd
  - ../../../apps/foundry-vtt-kf/overlays/prd
  - ../../../apps/foundry-vtt-mll/overlays/prd
  - ../../../apps/foundry-vtt-tjk/overlays/prd
  - ../../../apps/foundry-vtt-tw/overlays/prd
  - ../../../apps/home-assistant/overlays/prd
  - ../../../apps/mlx-portfolio/overlays/prd
  - ../../../apps/pihole/overlays/prd