---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared-tunnel
spec:
  encryptedData:
    credentials.json: AgAxj/JNvI95QBal9xJH3W4yq9i01oXIf/4N95C2avNo+o4EAVPBa7pEXddSMMLn02HzSGByoqGEoF44QFpTiJWxehApANL7vd66A/tPs3wRDXwmS1V8wqPjFSCzDaqKIQHJQ0dhRfusUniD1USVd/avBe4Epfu9t66kXWZdB9RSfR0D3+5A6Uymv/G3p3Brh3mPtULJNIxKa2IS5a4a29BVQLPvOnwxBSFIgz02tmVtpe0KHs9N1nkxOFxtPDPBtuPWGitAE7J3UVj8hjsI/hPteyt0+dF63U8nzNHJCluCZEgJjj/YYzLU/gol9iLFoS115cDGo4Atjdahv0979QQeniMvEWNN9FdvIazYqBAASTWl45xXrWJiowi2KQkRfUjDoMgic8MtRtfccMQug3lV7hud5ALg/13q17vVfawPqEYShFGnb/VvgPk89f0S5M73xKI81v02lWTmEB+MDhW0l5C2t/Sv12XluzPJ44lyhsLlmvMUaaEZ2yLMKiFoLv9Q0CgDH68BJbTOKy1rIu7+1G7nhlFSsdnDnViWPl5ggmgreW6D/h55LVeZLxGMGkTwaEVrVyzcE3fBxFuGUnzy/VR4OynbVfrw+q/FmaWn+U9Fs6RpAG1rB6D4+g6svx+h51i+Mj2kqfbnp0NK4furHwACo+bEOVSvym6xsPbjXpyAmhUc2DRFrakLvlUuowC1tZKMXJAFJ2JRVCQqFGZn4RCyNPTMJgNWjrsa7I3U4qSgrPVBXUGeuZ/DAFXxyvOrBfmt7pM2Massg6pHbYHpQVyuwCHY8oHrBkGXsMnb1xgNnP0YaCmLClSYfKxhF8zC1ar3k/AK3cqWOgx1dH7r1X9BNRBNxHlqOitmWNjW8G0/dZWC2I1FTRjHAaegN8IsmInXfvqxTDHYyJ8ehgAYIg==
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared-tunnel

