---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared-tunnel
spec:
  encryptedData:
    credentials.json: AgAAtwm7DhLB8oGiA/+pFmPAEojlatHCcHH8s6eVwydmDZTrgrN/ES4S0GX3Iq/jkDZwpD6ALGuHzWSoZ/KCZxfk7rIsPLsw3ZC7dV1WSjB4SFWz/vOXzlWbE7WyGt/2oNVjOZHT7OGdI1/qzHiM6bfrzrwRNuRq5HOqSSnPUGmJsogMv2PFQ2vPRRordnWcf4A3FRs/aOLgHF3Hvw0b4qG9KhKlCBxeH/89xTKgRMBg4NVa7BhIQKmEVpLESbVEzWKzQf5W/rXQxT9lg/T1oKD9yeIy+C9lxWuxqRmOJMWQp2j2bvtaMlKNXxclW+WsOuN/JmWJE5Nr4JfybHtFUopig/OzsfpRv13Hy5NjnnetV4B3d9Z2QFaYHJYjoBYOpW2cHf0AKvu1t732Y1owdQBr1K7BjWWAaOO7fu2c1yf24UBk2d/lNXnuJP01TDOII11Q/iYfLTEF2F5sa5q8LJ163MCTQMFRhr03Wp4TQteuHITvh/T3MiJRnVKMAvRoddyU517m05b8L3dkOLNFAj6SUaeZnsiM88bivc//++Z5J3lC0Tyw+S0qI4jppeBre4ChwfvEC94ec1Oz8mYRZhrwAPq0oCqh6YsH2bgiP7vzSeNP3tHV7vRUTxEZEOsGn0u+FPeRfqCnvzfkn8sB8uMFg8Ww6s7RKOdKAM8BLNmPMhy8sOZWMRaNq85DTdokN4svYOy0iv+hxXdpTVAbhQk5QO9ShAq+qGxqRt8cNIYFFOElUJT1bZK62k3mScy1QvP24wTQvZnFsT1tevYXeXxlDPzcouhtAfYsd3IB7/8tSDhrbTEDZf4aCtFMnofaMI1uCXcsJad0mYA/aVRVPlBmZSubDfDoa5X0Sht/A+6h4LjZry/sm3g8WJ4pkcsSEo/hhGHH6tDTkBfHAVkdDJNBnQ==
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared-tunnel
