---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared-tunnel
spec:
  encryptedData:
    credentials.json: AgByjbxz+kHf9b2lBwezrYaGl8XSIY12JRGgVYGhq+FOfSHDab6JZMlgQLamBnHIvmU0tyu3oji6apMvkR186gPxtfb5Sevxt34SZ11DpkvUVOn4HkGl0JTMHIXDcEIB8wkzUDodQ6ZziXtLpbpiw1qH8GF31Ql3jQ/r13sfNdMF5+9WSou7UN+Q6CtzcEbAdtFmecA62XXjbADFhiFKChhRInmSTa1VlmsKR048JkmxD2A28VoQ1nJtDq7eq/F4fVsKljFpNjCcMeF/NRj0EkAql823q+t6zytTbW2396+dyRn4bt0cEV9WyYY8TfgEzrXZ6JUpmhheBGEg1o3G7U5yFarXj4WhyuBkDhtU2jwPkDWig2MKLOcoiu9+HduhoK2gvrZYsHU+GOO9mZEoY1ZaF5ePEq0R/b0Htf3XKVGMjPpobxDt+5s/ixCRcAcY+O20LQ0DmVFMPYoS9spP9Wz/+pMgEwOVfDJJq+qtUhBAtZkeWghB4b2HN4VF7zvIuvP7X/Wx4q6BCBSkebjUPFQ/ea2sCB1AvVfCam+l9H0NoPxH1Q+3NrqbLZVnXd2ZFLQC8GleIOm2C1gOygtodE5pK7nJY3XKPZpuAGuYalzigyriyY+PEGGg/n95iGlXMqIt/KMP65D3nBJbG6ncmarSF/Gi7qyj2T//RwCq3pCwxTfgW9DDtMR0rpAtQ07m0mUtQ6AEeK7ANxfl1ACyNRiSmSBOAg5TqWDq2cahwa2vXz0xEd5/TOM2R49syfsm7ejm1TUUt2RODggJFSrJ4xM7/4MGhM2vfv1hJUIz7uCYYfGNNGxhUrgs+cHDR6R/rHk2FTvyPfO3MvlufpRdCSJxOdV5IXbfLUm0zlS1cVIm/Wxxj+JHUAAd9lExTAC/derap4wNReuvsyvQVSdYx7ubWQ==
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared-tunnel

