apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Cluster dev full deployment aggregates app overlays
resources:
  - ../../apps/bitwarden/overlays/dev
  - ../../apps/cert-manager/overlays/dev
  - ../../apps/cloudflared/overlays/dev
