---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-kustomization
  namespace: flux-system
resources:
  - traefik-namespace.yaml
  - traefik-crds.yaml
  - traefik-helmsource.yaml
  - traefik-cloudflare-sealedsecret.yaml
  - traefik-helmrelease.yaml