---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: traefik
spec:
  encryptedData:
    api-token: AgByFPbmB4r+K3Je+ca2scvoTRYWc4DH9JSuR37GTAAH5f6mIFeIjKlcbagoDZkjTdkKJxuSuRSjb/UGeatVOm1iHJSbmEP3L6NY+40GT2Sdq8B8sJUBfFfjifu4BAhJPHJi3T/V0kldq129oDp7nSZE5gMgsixkJFCuPERWZsIw2G28SUv/meANvO4ziCj+bSfGtX/4aLWlAb1z056mvFlW3mDRsu7MZe8WHn4/ucpBoAR1JSPV820NevGqek8Vv37jjUUYD5WWKlIiEHTsArwaWBp8xUuDrMt7JgHs7XJ66hjakDLzMnn/hvGQ2ttElaEopwJR9VCyHuxIScUmKJCs0UAUqwvvZ/D4huqBcT/lr1+eih4EV3ZDKylTmnCAsHOgPuQZBt0ygHajjqxtnfQL5RcM8i/0/hOYKDaS4PhrUD9SXJU1KHUlB1fHfob8nTp7U7YSjvAR6bswnA2zvDtSaZPyCTwtH+2H3cYfYkmoGfwCyN1KkDmcDuSX4ITMir38a48YWc2ddEhLFsi3msUz8/0TkScmy7qnFMkNuJUbCj/NN7EEv5dAow2ZUaKpzVopFugLm/Nlw80KswbVkML9d9vAN0EQKOPFgs5cgZAEFFCtfGvPS9z1o8sv6pLspo7FREGycDC3we8syuuYSmdw2tQI7NMSnAcZ36YsBSb20/p+VsQOaRi8RBq7KE3Vw5bq7mqZIjnumQMcox0FMi89vNfErgqWgZ962n1CBc3mKjfTGdNioU5z
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: traefik
    type: Opaque
