---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  chart:
    spec:
      chart: jellyfin
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
      version: 2.3.x
  interval: 1m0s
  timeout: 10m
  releaseName: jellyfin
  targetNamespace: jellyfin
  values:
    # -- Number of Jellyfin replicas to start. Should be left at 1.
    replicaCount: 1

    image:
      # -- Container image repository for Jellyfin.
      repository: docker.io/jellyfin/jellyfin
      # -- Jellyfin container image tag. Leave empty to automatically use the Chart's app version.
      tag: ""


    # -- Define a custom runtimeClassName for the pod.
    runtimeClassName: 'nvidia'


    service:
      # # -- Custom name for the service port
      # name: http
      # -- Service type (ClusterIP, NodePort, or LoadBalancer).
      type: LoadBalancer
      # -- Configure dual-stack IP family policy. See: https://kubernetes.io/docs/concepts/services-networking/dual-stack/
      ipFamilyPolicy: ""
      # -- Supported IP families (IPv4, IPv6).
      ipFamilies: []
      # -- Specific IP address for the LoadBalancer.
      loadBalancerIP: "10.17.18.101"
      # -- Class of the LoadBalancer.
      loadBalancerClass: ""
      # -- Source ranges allowed to access the LoadBalancer.
      loadBalancerSourceRanges: []
      # -- Port for the Jellyfin service.
      port: 8096
      # -- Name of the port in the service.
      portName: service
      # -- Annotations for the service.
      annotations: {}
      # -- Labels for the service.
      labels: {}
      # -- External traffic policy (Cluster or Local).
      # externalTrafficPolicy: Cluster
      # -- NodePort for the service (if applicable).
      # nodePort: 

    # -- Resource requests and limits for the Jellyfin container.
    resources:
      limits:
        nvidia.com/gpu: 1      
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi


    persistence:
      config:
        ## -- Use an existing PVC for this mount
        existingClaim: 'jellyfin-config'
      media:
        ## -- Use an existing PVC for this mount
        existingClaim: 'jellyfin-pvc-media'
