apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - bitwarden_helmrelease_dev.yaml
  - bitwarden_ingressroute_dev.yaml
  - bitwarden_sealedsecret_dev.yaml
