apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: bitwarden_helmrelease_dev.yaml
  - path: bitwarden_ingress_dev.yaml
  - path: bitwarden_sealedsecret_dev.yaml
