apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - pihole_IngressRoute_dev.yaml
  - pihole_SealedSecret_dev.yaml
  - pihole_HelmRelease_dev.yaml
