apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin-secret
  namespace: pihole
spec:
  encryptedData:
    password: AgBWZSVExQtGmFbgDOpGgZfWqZ1QivKFOF231Op2u2Cn7dGEq77vqzmx9uzkfTFwACkQjm74SblsyTj7f/oHmkXubD10e8njoEC8WAHjng56V6rEHyeBp2QCEfBEckxuEdO248H9ShAP2hcRDlqLkN8fR377+9I1QvreBSnSXTDmFA25TiXOT1u1tkmKzQu1I+uiaPDlTdrIKCJYAD+Jm32bROIgF2ZwbgfDRb6cdwMK6y9e2K6H6vVoRQ6mzsWnjyxA8ao+e7675qnBtPeKX/atTi6KIb6ZyU0vG4/A5EnlfLpxdv3XmCwft/GGp2guPuXoUxXdDtuCA5zT1+VTry94eEMdyfQ1i/tjFxBmjWJkrv3dHw36dtmEbSfNSHLscDKFT7FkAEOYV6WiL88I8o5boOer1846ag0eO3EO72JWw9mxIxCxkR34fB9z//ij5pD0AvzYJwLAXy9ZM4FcgJesw2Xw3eEh++NHa5Uv2GyutWmMQiXBUNfCt+X2PUEtYueKTx7EtOo9fI4o3lYV7yNysP5HcKaPmaSNAw0I+799MQsvmbcf3srWrSQAHUJlh/k/+4rof+MoRr5wp4ibXipLOhDEku9KA0ha8YmWT8/Cd4j9Ju0oBiKGUoJPByKFo4s5BIvKDPpuF/9zg7xqZ6IcRsIi6w37Cgjt5ofs2TVzTDbYkHjrw58fJMM4iYQj3rWp/GYrnMkayTSX0TjhmA==
