apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  # - longhorn_RecurringJobs_dev.yaml
patchesStrategicMerge:
  - longhorn_HelmRelease_dev.yaml
  - longhorn_SealedSecret_dev.yaml
