apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: flux-system
spec:
  values:
    defaultSettings:
      backupTarget: s3://longhorn-backup-dev@mlx-home/
      defaultReplicaCount: 1 # Sets the default number of replicas for new volumes to 1 instead of 3
      backingImageMinNumberOfCopies: 1 # Ensures only one copy of the backing image is kept globally
