---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-cifs-secret
  namespace: plex
spec:
  encryptedData:
    password: AgAOea58OK7G7Pi/NWj6sXjynf8IVNiEFHWddHd+N/GRo8/3Sksyp13AuRJS6jV2NlFB7aqR75uIBbG1nm5RNMC7I67Nvn4mhrNm+A98UXP+4JK2RhBMHxOZo1GNc/gNAp71Jc+3zDHweaISiw0xBAZA5ZNJno53mS6AxxAzIv1DqyJKTTGw3O4JEoeJ65dTaZ4ShRDP97tJIluy2AWNeixH/ookRDWE1YmduLOMUbx0X5cVWn4H94pys1GPdbBZbCgdJ4PW1ry6PjPOjFQB51HnmTggbRt9iFJQc/MCJKKrSEXKTe1QCcSDh9zQuOPKU0WV2jMdN8KHsvME9O+U6A+Ccc3qzy3mcezb9O8K5uTMOudmt0R1NvPCvVAAHDwk2JLwLxrM5Ft5tDkbQnCNQYgR1ebzVDNKSti9n32p+KaOtzsZ9omcrtPbArK3n3olS5bxmlRJKr4YYp5H5iZ2fA9mP9DDplrnCyypmVAMiKsUiUg4M4JDsKnehQBxN5cJO9B20nAb1lVVPVuGp3B3ebspY+BtQZxon5A/PMZ+p9Hb+gRnoyrAauTX+GwD9AhMm4EqiKp6Y42i4PgBCZbLSxCgy2NsL8EeV54CBskgotlg/ngkKR77auWJK1PibQ5GCrQXISGe280UQoeEnRATkK1vrZlXybV0LGWvmGUCy1VxFDD49lgfOj3W8/sJaWNrLiVxbwtcaQ9fmsUwhOeUamvRLA==
    username: AgBSarnokekBuCTiI5Oqznpuz1Dkr1sKgZCtGkO9/gXzfI5s32fQUukQa0C2OarBu/0JUEYLtg7nao7jTK+mAMfdJM5Ou8hoChXxZuVD4ziNpfI/Ov2RZGKn+6dmC5PR+E8AMRjjgk4qRGPFi4eNiiMbYkT27lFDJa/vp8JmoFVnF9v2dnRVmcGiv2imZamO80Nd444f7giL7COseJSQcQjMvyuuCRaDPOtBahEKITfFVfsg+ILxAAHGFR/TiDlmPlmy1tfg7ZNEObMlBKsjuUzhA1wSKPHqT/7HlbahgkNuVQ+bH0CEGX3Uy1EdZWvFwWXfYCeA0qa6KgHGnH8Ev3YTlp57VCUkuQ/7/TgRE+p929FUcf7H/AT9r9yo/V9SkfMspcRZsn7iJ2KRc5pqJYSVlV/dptNrqIuxv0vAHZ7wznV6gY77BdUB2diZxmYrNJYS4vJsM7k126xA/83nuPRaj1XpbPvZic5loDIRUgqAFhzflLGPUDDoYHKr78c/kLEPWB2IQqetOrpnGCz1iOFxOFJblclXXy7gTS0h//ZkvjD8S9MlGO5EVFgt6zi4E+8HAOythkAeKt0nPSs0QbTL1a8iPp7d62+E4wpICGp4zL9TD/wFYoHgYpS0C3OB5HLLS43WeKzLyu4+WR60WAyHz3bkBpoXBgDmV+fNsKS2NRoXiAkii3zapyXLZmAoV2CZFCEz4ucUag==
  template:
    metadata:
      creationTimestamp: null
      name: plex-cifs-secret
      namespace: plex
    type: fstab/cifs
