apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: "2025-07-27T01:21:49Z"
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: foundry-vtt-mll-secret
  namespace: foundry-vtt-mll
  resourceVersion: "61003011"
  uid: 952cea79-e847-4334-b029-da4c2f28a79b
spec:
  encryptedData:
    adminPassword: AgBXlfCsAnHHRVcpUrM5I6T3rNPWUFLvEOfWUg/dacplUbr7a/0ppqsGHbZQMBEpxiah0tLUnVJFNFK3CQzpPaUVkQUhPhPSBZ4nyXXyGPqShmar49jm+wo9hDsEIZgWrJzKzLshdzJd2GL7lYTmEEdpu9xqxpv3QQfEOhOR9g0rhMHzwjreG6HWAWGvkHYyIDI/OWiF0IDFVBWt6lBMaWXGnvZXKB6PdyylUgnhuRLgxrEnV7AeuNkKnmIodOQ0BztYq2voKyo0j3zB6Dn65JUI6wNhCq1ULiDgMFbnks54XsLSSyKuM5SQcD3Qc/JEQV0Kx5p2a/RsI0HsROcEinW4igHd77RJx+H44e2fGf/icMX46EMmVKRTS+z5TEluI+k0SllzNmV8G05KKlY7gHbtuhdFvT9yLXcAVaJ6RBxFnwCHur6K+mpak1DsNjDzTak7hrAW1CBiXLIQUaDmfl5RmpStRLpCVzB8D0LS93+Tsv1iZT3SGlry3O12q+sIHA2D6Q8zI31mqUZukbhJCu3s5sKRvUNfjg1CsNbE2HFGOOeUY93uD0pWPGBJs7XpzU1DyvhPXdL8DngsDYLxqmKWZEmShwU5gmQML4F4kF+ebs4rXYFZsKRQ1mnXTZK0Aue/4gHgsPF9bH4CeneooXvjqo2zg4BZbxqLrzbj5uxL0CBHGA6nPqxQGWW74JIkkurmWLvTmAKfbtXxW3bKkg==
    licenseKey: AgAs8gP5V2mOkb4PDLVLAEVC+TOv4/GHv9F4TQUb4uRXkAKGTyCzFwcXlfo2g/1tzwFpDu+/KilmO7QECWEWbBURdhT2HeBkuKJS56etoxhbsS8c92P3igTaIKY0Mn6SqWNA7DLVJRkoxhlUF8+NMgKQvgP6aPgbfXjVJdJ0BhiZCUwGfPXI8kHM4mpR9MttxxmACyUAB0r125a295NOPqm9cGhWmpXCJwmrBEv65yj/c/7bPrgVYv7VaLi9qIdJTfv28DZiedvYMHxj7QdSYgJ6K8eS62HuTxSes38ysTrb43t97Ko6Gg4/vWTyRacWSGm+JN/ptBZWaYbYGelq1eMu2aOSSpj+EgS1T7gdCcIUhAV2+XM3n68WCLNHoGi2Db+W0AsA5RVb/CwyARj5shbGM6Yrnvbi3bd8OH/4qwi9XvEmqIqXv7zDseK5I++7Xhs0y/DSp6DE336NZq9ADYzNjehk5GwopxOHMA3G5Ddv+jTMUeJPBkn7uiso/UsG5sO+R4f8stZyISDhcDapYI/nWGYJ0SywUJMeTKA5VKoDPI/ZR/12SO7Mqu58+a3ST/Fh78B4x91QtRY2CQHDRKErP8630hy3LBIdpvg2n/McWZud+1ssoVoNw7RfIB9FGnoWNSA8RefG9h+0BtRCWmMWnmu/AptQPIzAw4LutV7vAS3jIrlm95m6qF7rFc0t7NDlAICC2atplMCpNm8SsYJXfLeD+7XT6/S5mH9P6g==
    password: AgBW2zOov7VG4uQ6N7cTyvIpelBd+8q3SHwok0lkiF/gEbBorFKQU/jeWYNfP3XvRwH1/BCMRi3w0K+6F6vRyZq3a6RxlJmcwt7OAtbnD4U9PbvTqo36wVsA7cVCKWU/GKAl0x13pe6oAT7T+QxJk+anMrJahJipQGAq6U8zsE58ZjtOlDiDzSuRMFtwdkyQSMKB0EuspdqjGLb1U2EHu566K1XtEoclCEnWKzmGixQqzNsBXjgTWb/LSB/JqqoI1NMgEkO/T+RUMxEB3Gh69m1MGdkGtcuwfmnGUhjJG/s1Urmsp0TbKDoUdF0ZaU4kRsRIdV2efHHAqxnhyjgv0sTMi2ZwWQd3bxNC7sfhnL6Ha4MDQtm0WKtsHzfJGlbI/9wLq2HgDZJQdlVloln8pLtnZwJrriEd3OoseHkNn3P6C7QCo0qY+2rnFWnMw+ozy4TDS09A3PTTtr6VQA7v45DReYn4bLPHFfK9v2HLarvioBLhynlxPs2BgZ6VZ1Px3KFY2ocMRmPtHeCZpBEtFHWO+AO6O6DPGD/XQEmyFPamY5PAkSj0wYbCJbRvkGpP9vOkd9ACy+p1Nshov0kwMTEfDcQOCJJwpxRVdfdHwcg1DwfwM/rBGb2xLYfmILZ+9mcj5EPLl/aV+qST1IfW/E7Jq/FFPwjaK8Az/9is7hgl5zwzeho0xH/MqW7J6E/8zeUqefCvkNGAOHxlFoDhpQ==
    username: AgAXygBPEMcXAP3TufLP7Pq3DV96Tt9bV9rPRn+ZcA+9Ght7c44bA+1Ie5GQ9ymrSPaPP+goM14rVlR7xk5TC1U+/rZQmMo3WUurEbtSZHExTdkh05HitK0A2i8N02PJ60cZ5HqP6A46ojh//rBZaI1BmMPIpcSLndiSlOt8w6kyCvm/cohZf+73EQwH6cNlfH0XHUC0JXlSBqaZ6UBEo630NkHoVQNavUWFujOYQ7vgrFJ0JrZBCRRIm2keSKVGugva0eTcHeNQ+umXe/FZiIQ9nnfSQcGT8EnKVcLdbHRQ7qM6D4eaNT8ygSPqsSxRE2fHym0lF1xubWe7lTWDFsAM87QGSJe2kZ6XArLN2d5Sl/L0wVm6NLoRBe4UQA54b0VGQG8pAd6JIZRR7CeRTYjdXasHH9pUURA63xrDdGp6TBeiSbc4lLunJruU6nszn0p88kEZrqxFQB+JwlPMPqrspgkFlgOvQGaPO0DS+hyiGPpPipHTY+fHJzFVVgrygiurMWx3clT9m//5FTwXyOR4B2gOsVU1wQytozVDpE+6wK/wrEDAmG66+QfcZJwtAcar/mjVG+cCKzbYBBTwNXU/hYQxF1TOZMZYe2zP3DiIQEDKVNivJw3sdSzKJEm7csjz1YsO5TW79bf0Q8MUkVNJOhZBtHm5duJtkZX+mzR54hLx1CiwP8iZBDXgwmd9iAKvifhBML0Zrb9UNwCAmLKYHvDBXaFPZJc6bg==
  template:
    metadata:
      creationTimestamp: null
      name: foundry-vtt-mll-secret
      namespace: foundry-vtt-mll
status:
  conditions:
  - lastTransitionTime: "2025-07-27T01:21:49Z"
    lastUpdateTime: "2025-07-27T01:21:49Z"
    status: "True"
    type: Synced
  observedGeneration: 1
