---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-vtt-mll-pvc
  namespace: foundry-vtt-mll
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi