---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: home-assistant-kustomization
  namespace: flux-system
resources:
- home-assistant-namespace.yaml
- home-assistant-pvc.yaml
- home-assistant-ingress.yaml
- home-assistant-helmsource.yaml
- home-assistant-helmrelease.yaml

