---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCRWMTMcvZ7OWjH0zvM8JwJzee3Yih4pClAaZfwGVbYepv2tjyffdmNlm3DLCw0f6p/R8jqkmzIj7jWqftUi26+LFSKMqdDa+tdACwj43MuR8i/Q8mEnOEML4Mt4DhhLesjV5a4HqB0Kih5W0lM/PDYStE3xY9shq6aPkxZkCGWfBNeS4Fs0XKMazmq1dBE0AWMbdYTiIwozDaEsGSpngN8XOwNP8CPmx1lqe+Z67bP2kEW98QWZlnTMoHjio8e/Lwb28ix4PypM7NsFMhujtSk7tnKfraoq+bv9dyLwatC/v6FrjNzTi1ZWOL3ovmM6JUvy488twOrqxcS9BXqp6c1b1btAQK8ThCVFZFlAB7vJNf4pybAnzfq/sUMcyf5oNN2jf8JenKbreEtJxgILnnNAjvbdb6Wl+SnczW5xdewgLuqb5URAmuIfU0YylPrhYgw1hMd846cjtK7BSYLLlDFJf9hjI9B0sG9EZS54YydCuDtP02OEIdCrH4S3qGrGyqwipjBCMom0gv8UGBZYxBBALL+cFCkejNX99Ckvb2B+ud2EMmRd+7i7kGWXTqhTlhA9RNEqwbg/GI3wHiF3QmPdFi93TYbHAigoJ/gGTdFlh8MQHMPbKGQdw8OAV0/b5nLM/cZ9ZVwx9+WCJrpVhfbon0BFRiY8T95IUvUi2pUM8UW5WtCiStN46XkF2fo0rSZyX7dL/QHoU3yO4HTzjppAIxm8xKLKosf95QGHDIprDU14iQaLlYC
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
