apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nvidia_helm-repository.yaml
  - nvidia_helmrelease-deviceplugin.yaml
  - nvidia_helmrelease-featurediscovory.yaml
  - nvidia_runtimeclass.yaml
