apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nvidia-kustomization
  namespace: flux-system
resources:
- nvidia_RuntimeClass.yaml
- nvidia_HelmRepository.yaml
- nvidia_HelmRelease.yaml