---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: foundry-vtt-mll
  namespace: flux-system
spec:
  chart:
    spec:
      chart: foundry-vtt
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: mlx-charts
        namespace: flux-system
      version: 13.345.x
  interval: 1m0s
  timeout: 10m
  releaseName: foundry-vtt-mll
  targetNamespace: foundry-vtt-mll
  values:
    ## @section Pod Resources
    ## @param resources.requests.cpu Percentile of CPU Requested to run
    ## @param resources.requests.memory RAM Requested to run
    ## @param resources.limits.cpu Maximum CPU allowed
    ## @param resources.limits.memory Maximum RAM allowed
    # resources:
    #   # We usually recommend not to specify default resources and to leave this as a conscious
    #   # choice for the user. This also increases chances charts run on environments with little
    #   # resources, such as Minikube. If you do want to specify resources, uncomment the following
    #   # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    #   requests:
    #     cpu: 500m
    #     memory: 512Mi
    #   limits:
    #     cpu: 1024m
    #     memory: 1024Mi


    persistence:
      dataDir:
        # Set this to false if you don't care to persist state between restarts.
        enabled: true
        # Set this value if you already have an existing PVC that you want to utilize. You still need to set enabled above to true.
        existingPvc: "foundry-vtt-mll-pvc"

    ## @section Service Parameters
    ## @param service.serviceType Type of Service to create, defaults to ClusterIP
    ## @param service.port Port to expose
    ## @param service.protocol Protocol to use
    ## @param service.loadBalancerIP IP to assign to the Service if type LoadBalancer is selected, deprecated
    ## @param service.loadBalancerSourceRanges Range from which to choose the IP to assign to the Service
    ## @param service.externalTrafficPolicy External Traffic Policy
    ## @param service.labels Extra labels to assign to the Service
    ## @param service.tls Enable TLS for the Service
    ## @param service.annotations Extra annotations to assign to the Service
    service:
      serviceType: ClusterIP
    #   port: 80
    #   protocol: TCP
    #   loadBalancerIP:
    #   loadBalancerSourceRanges: []
    #   ## Set the externalTrafficPolicy in the Service to either Cluster or Local
    #   externalTrafficPolicy: Local
    #   labels: {}
    #   # Enable TLS for LoadBalancer
    #   tls: true
    #   annotations: {}

    foundryvtt:
      ## If an you have an existing secret you want to use, uncomment and place the name
      ## This secret must have 'username', 'password', 'adminPassword', and 'licenseKey'
      existingSecretName: "foundry-vtt-mll-secret"
