apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: foundry-vtt-tjk-ingress
  namespace: foundry-vtt-tjk
spec:
  routes:
    - kind: Rule
      match: Host(`dev-blint.sakagegaming.com`)
      services:
        - kind: Service
          name: foundry-vtt-tjk
          passHostHeader: true
          port: 80
  # tls:
  #   certResolver: letsencrypt
