apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  values:
    runtimeClassName: ''
    resources:
      requests:
        nvidia.com/gpu: null
      limits:
        nvidia.com/gpu: null    
    
    service:
      # -- Service type (ClusterIP, NodePort, or LoadBalancer).
      type: LoadBalancer
      # -- Specific IP address for the LoadBalancer.
      loadBalancerIP: "10.17.17.101"