apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - jellyfin_IngressRoute_dev.yaml
  - jellyfin_HelmRelease_dev.yaml
  - jellyfin_PV_dev.yaml
