---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: foundry-vtt
  namespace: flux-system
spec:
  chart:
    spec:
      chart: foundry-vtt
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: foundry-vtt
        namespace: flux-system
      version: 12.324.x
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: foundry-vtt
  targetNamespace: foundry-vtt