---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-kustomization
  namespace: flux-system
resources:
  - traefik_GitRepository_Kustomization.yaml
  - traefik_HelmRepository.yaml
  - traefik_HelmRelease.yaml