apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: "2025-09-17T01:27:27Z"
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: foundry-vtt-tjk-secret
  namespace: foundry-vtt-tjk
  resourceVersion: "91034886"
  uid: 6f3cb854-6632-4809-b260-f30c8493d199
spec:
  encryptedData:
    adminPassword: AgA5ja62tZDsy39qo3BWKr6xbtYCExznaQjmjWl6uOougUEMDstlQWc+FuCjbi3oOQ9rdqvCB9wB/qHZYDZIhSdzH4dhZxbH21fXKya7YQnluIKhVo43pMbtypwru0hZTLjsVMD4JyDqow4XyWyUlstg16ExkVLnYQXD8uQbCGEmsolLVU7MoNbXQFsoAqIyIWEA0tk+m8udzOb2VnNPhA4WBQt49O3zfSUjlAr7B6casq4Gl17KWBw2V9bSyjuL2+w/eKorqT3T0uvmj3kuGmNmq16QhzNG8/hjrlosrqU9oVPnRsAySelg3iMaFlLjtzlZign8Wo23XBAGsqUn6WuQngg+X/biOga027J9QENfiRNGzBXP9FGlGXI9Rcp8j50J201/Yk/Nx5JAMfZl/9lOsBcM4F7kdCRv7u9qNsfqwdRoJLmCWJkMrjRR3K9Ne/7gS6lxS1c/TwCgBzS1NnqwaGdEX47gRqegv1x9hJxhTxmvAEGXrHkitWOvpQv5YlQFh0F3eedxfKndkUloLsQ3OqROejlnZOAqqui+yf6/Lzdv9UP8hcZOTTXQBqrEs51XDHHNx1Bc3+aclBhHeSLLwOoNSkvKNwiQfFNpR1s0/Ald+zM023WFeYLuSTYo+9S31iSkFkXA9Lvc5wz5oC1g8NoLkW9pzEfIX59aV/SXelWABY81OWLPxDwIgVxd623AMWoTiFrWarIukvOHFuVe1A==
    licenseKey: AgBslg2gwrzFfoNQZjMWQG6aXn0dQs/9I1RBpwHjd8bJorf/RSj3FTjClka5uSmNU9R8Be6saHVLZqVOt517EvF1ilEYtKOwDOL3nX1YKNrFS06pSPQ5qmhm2WCJdmL9URZPPq+0ZKCYZr1PxwWIhIIAnqTL7+qCs4nWoOKxMRivHNvm2SrwB8YIwA3DfmZhhSeP8DZEmLoU26Vfnexn1ESblDU4cCaC69JDIOgOKqJ8HWWb+wO36xWcDpymGVyarzf/6ltLCkN6OGysN+DLfOL5SxdGwS505PFSvj4wD317gxMcHoh2j5ceolcFC21h2WY+GaIsIvJKTk+cvVKAJcBDJTC+82iKMezkVoYIvoSks2kCUa05wHOESHc8h0AQQ+rFWzT4mKRawQdBvcO41fDb8xEYkg1jIxVH48aIeCaH3YGRKn+Ooo+jhte6Y7KqF2tqw/EAvOzHHyCHvyXrEAy3cUJYyVngztDJZB0ECabHCzEV60j1JNNCLlwrtduGXEQXXG3mM4Y9fvG/bBoCedCkf3wl+XfXYjPSNtfp55NYr9dJy1g3JKTezkvkQBU3nW3J/3Tyych80nbm3kaG51dyoVvU63wwgbIbh7EKp3WHYWYU6clqyZEwTtPjksmhj8+utXhlNjCXmcW49h/2uaHtwgDZJLU4kUXjXnZT9OAqGSv0TNG3SIG7btzBNbDrgKsrM1Q23hhCmaqrrpg4N9l5QpfFgxdNsOG9fJUKbg==
    password: AgBCn2L1hqvqCxTE3ziNNWDqZIhVWyF0NneKjwH448YYNkI86ue1tsbtnWTkFRbcYEn2ajSCSiulsoE6tjVdUJTsumB1xmxXR5QXFwfLBB2tBe0vE84McII70LIvE0E2x4qd9uwGNRc4NERHJQyz3WN+A56RMP0er3M0UeX2xaH0zrqjnjFptIYxqZtMjLJNZtPRsqTBBdUfByNR4NijvWe/qcpqN9L3O1EDzaeJyaJEeokkzKZLm6behAmQBdia00R+E0icMH72d7pB4Q0JtaoFrnZYDbX5ZxJ8Zk2VNabHEig3zd8WRebabPvb6q1wLN8yoZBLB/zd4mNF7/IXjFCUBnDacMDY58ETfPoagIey2zuXWW/4o9+RWX04xBi+M4OsN4ajpCj36vE1doUrrawud1qP4aAc+Xdga/SHUea18/UkwKUHthMre9xn/AQ2LFKYutIgag2T6fAuSjuMJ7Gjx2wlbQed43F8U8wyECIyr5W0AqjenhfvSxoYaVz7D1yr72p6TWV1yLTd+Qjvna5rCi3CcNApE7IJnNoHYP6G5vpWda045EZIkROd2C9iDcYQnk6ZmzRC9D8NlvU1/eldNVIDk0/XbVHjLrNV+uNokC/olv+qMHQD2Td7dutqyqHasSV00sepAQlFqe66sKvl+avS8IdmBjhto1sDesZG8Gix+pIYibNKXJpr7ke/xgYrddBmb1ShGFr8UM5sjg==
    username: AgCIvqMDbnaZKa29llY9ijQAdkHuxRxX3ZoXaV/xNdAtQJj49bDm1jtl1Ns0ULy1/ewqt6R9aaIAoyzeOTu1JFu9eUeCWmMZJiHw+wF/hDLeCo4QqTDgEwlURiIv6/c9xVHTHybN6C8EUi9rehtlHq8HeARStORnWOoAMJvUr2QIGmVJAPRZuIoCxIN3hgZdGoXMYzDwA0tgGgOXJxHQve1usVD/xXX1z3OmX2gz440OWN/LQPjF8hk3YQ/2B8JHnuBEEOR/Bo9eieWJJ5wRvXcqaL4ui2owFrZjjW72OUTOTIAlGnW9ulXz+VD7qjVQeB3epRdFsYprJ8wm7OVYTjisNdXbnfUc8VsyaRH0xhz00UVOS+457pssxQ7r2fQICWSSn3P3YHkq+Lpjw4RH4iLyXQ9iHrrygCEgXkRp9bG2ABdjmGBNZNQEzlGs8ZQNcF6fWEftBlOAvTUpXMmdlmUgHXtI4LKTnODpDBLC8rg7QuKh0XrUs7fEIWDgXOW1P4PvbcXqW/pBp91iEXbg2Zlj648bJc/5EjCVSjVsbfIIm7mY1/68iH4SiUTesE/1JwUri19Luh+VV9fgCi4rtjpAwTP1rCpAoETYsg3sdnkMgjmlSeFgs32qQxc8RamERvrsvkblPhL9YCbY0LXJFQ1yZBzPcbQTdAdfmgmXSBOKvniaOwHfHRLWGqw/C5nVPXBJaowrKdXXrNX5uzSBrM8w814rzkmCMk8u4Q==
  template:
    metadata:
      creationTimestamp: null
      name: foundry-vtt-tjk-secret
      namespace: foundry-vtt-tjk
status:
  conditions:
  - lastTransitionTime: "2025-09-17T01:27:27Z"
    lastUpdateTime: "2025-09-17T01:27:27Z"
    status: "True"
    type: Synced
  observedGeneration: 1
