apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: foundry-vtt-tjk-kustomization
  namespace: flux-system
resources:
- foundry-vtt-tjk_HelmRepository.yaml
- foundry-vtt-tjk_SealedSecret.yaml
- foundry-vtt-tjk_PVC.yaml
- foundry-vtt-tjk_IngressRoute.yaml
- foundry-vtt-tjk_HelmRelease.yaml
