---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-vtt-kf-pvc
  namespace: foundry-vtt-kf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi