apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-assistant_helm-repository.yaml
  - home-assistant_helmrelease.yaml
  - home-assistant_ingress.yaml
  - home-assistant_pvc.yaml
