---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: home-assistant-kustomization
  namespace: flux-system
resources:
- home-assistant_PVC.yaml
- home-assistant_IngressRoute.yaml
- home-assistant_HelmRepository.yaml
- home-assistant_HelmRelease.yaml

