apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: HelmRelease
      name: kube-prometheus-stack-release
    patch: |
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/retention
        value: 3d
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/storageSpec/volumeClaimTemplate/spec/resources/requests/storage
        value: 5Gi
