apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: foundry-vtt-mll-kustomization
  namespace: flux-system
resources:
# - foundry-vtt/mll/foundry-vtt-mll-namespace.yaml
# - foundry-vtt/mll/foundry-vtt-mll-sealedsecret.yaml
# - foundry-vtt/mll/foundry-vtt-mll-pvc.yaml
# - foundry-vtt/mll/foundry-vtt-mll-ingress.yaml
- foundry-vtt/kf/foundry-vtt-kf-namespace.yaml
- foundry-vtt/kf/foundry-vtt-kf-sealedsecret.yaml
- foundry-vtt/kf/foundry-vtt-kf-pvc.yaml
- foundry-vtt/kf/foundry-vtt-kf-ingress.yaml
- foundry-vtt/tjk/foundry-vtt-tjk-namespace.yaml
- foundry-vtt/tjk/foundry-vtt-tjk-sealedsecret.yaml
- foundry-vtt/tjk/foundry-vtt-tjk-pvc.yaml
- foundry-vtt/tjk/foundry-vtt-tjk-ingress.yaml
- mlx-portfolio/mlx-portfolio-namespace.yaml
- mlx-portfolio/mlx-portfolio-ingress.yaml
- ddb-proxy/ddb-proxy-namespace.yaml
- ddb-proxy/ddb-proxy-ingress.yaml
- mlx-charts-helmsource.yaml
# - foundry-vtt/mll/foundry-vtt-mll-helmrelease.yaml
- foundry-vtt/kf/foundry-vtt-kf-helmrelease.yaml
- foundry-vtt/tjk/foundry-vtt-tjk-helmrelease.yaml
- ddb-proxy/ddb-proxy-helmrelease.yaml
- mlx-portfolio/mlx-portfolio-helmrelease.yaml
