---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lgtm-prometheus_HelmRepository.yaml
  - lgtm-prometheus_HelmRelease.yaml
  - lgtm-prometheus_SealedSecret.yaml
  - lgtm-prometheus_IngressRoute.yaml
