---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCVLvFg0YCs5l4tMm4yAeJPA4xtaQibueIdoXvlDzTYVsXTqLOYe/Cg+1fPpAPcFOlzaolNTt9yTcE3mgki7x3C1pcFUViVbSaB9UUlZgUltSXKK4Q/+kV4b9dZwMUxeW6tBH6djd9/qT/bFxFReDRlAAdypqxD+/LbuIWmmByICE1Bqij1BWmuu9YoGFAY+P8vFg+Wb94D+bcLRIWBC1TZg/6N2Q6fb+SBZKCFpacy1s8+d7Jhi3cv31IhTZYP+WUqnw369dWAsmnU1jYLlVJyIKkVByR+COfEVbLcHkb1s3q0EEXV2b9j+/9JrWONj6pnORUxK2+46GVCTA2OraOwmCYwRigEcXiJ7VD0KZ1Xyg0ZXk7HbL7OWDTcz1TAfMZOxmq5P/4w/ZOcf8fCUf+ziWQyRhzPrBOO4F/PTt9loMMOYRySPVLKBz3XhRmkf2YrZWZj+UE5lZC3TdcBLc/ogX4SRFa2jEAnp6X6bjkTByGy1rEWHKYQie0I73Kg++0PrYny3mI4xriyvIH7alaKj23/kQxzvWyPmGPuGbIaJaL7GPhoFbNtjz7deY9m+XwvLC0iwMq2wdNo7URX5YMTEcxuHuhggXVPm9Jz9xegWa+34aBpzUlyLZTmomHSV/i9XC4Y+BVhh9iQtuDw3wpzPzKSnDfPr3ARGDntm3Yh4hG2pg9kzaArs6CnnZ921MK4tJCN11q0om5mhd2CESDs8Q==
    admin-user: AgCW4+ev35wIFwhpjkld6pl3WTEn3NSleURT4iwoGGSCNHEjQ2BZ4jrQTRVe1L5q6qJa9R5Nf8YGZkDACD1pyqaakuwQdb1CllC5mGv1ppW71aJ7u1ZQ/+9dQjG94iauil8rdS4KtA8gt5Txrq74D+082N1ezPsRoB89A+QaHOXBOo4OmQRQfzLv240kJg92uQOpZI8V+NDAouXWR9kOsuW0nT/F9RuO4/9eh5obqlK3YYanVWIXiMWKOq4IGyoaJVN9P8g74HpeXn1qwZycWi3egdT80CTklyhGGlDNQ2tx8u5xishBrE8wU1fkf8FmfnfryL+uJXqeVG5A4Y6hFKUZ8GkAd8c+DmWwzI6biT3PhhiK9TzBcDb6HHH4fPbTy3co+Ru22zO0zWfrkFmgmnoa91oxs880uLujcckT3lszHFpNCBTWZUxjmYjoMdJ/oCLaQhO86UsGX0Yese86mBizXBtLTjpxXPeEqG+hOkPH1M67/T51bzIhemOvhdNIHVi3iis+sKbezMZaVUylJeCO+b3shhxgdLG+sah1vCadg7AY94Aon45seGzz6UFfQQ2rlVxLrFdzLu+e7WN86VdK1YsfuHYZ6PG9WslfgItNZmeqwpdLOOClUqQqxJTTL7Mbo4q8lbOX4U0+k74/am+xKYHy07Ps6CFs09Y5bZr6nCYckM6+YsccztMXeRJrUg+LQtdyKFSeHQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
