---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # monitoring / observability (LGTM)
  - ../../../apps/lgtm-prometheus/overlays/prd
  - ../../../apps/lgtm-loki/overlays/prd
  - ../../../apps/lgtm-alloy/overlays/prd
  - ../../../apps/lgtm-tempo/overlays/prd
