---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pihole_helm-repository.yaml
- pihole_sealedsecret.yaml
- pihole_pvcs.yaml
- pihole_helmrelease.yaml
- pihole_ingress.yaml
