---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin-secret
  namespace: pihole
spec:
  encryptedData:
    password: AgACrUJhGv2C0nWeR5ND0FyLtKLt+iCzefoaBgRuihKpnRmUkg7+DPkvJOdl2AXiKC7tZon4KFY/vlhLlpqGTw002ZrKQrh8P/3BizYxE0nt/rMg1leKRjq2KRQnPUM8leraCF7ZdC24FmN595m/H1fUuX09UOH7K/kqD9wxgF99sA/DUmfRKuBveDNdpjxC/DeS0DsyiMDF9TUKSMfsRcnFh9YT5fpcuH0LsMiD0cPguJ34BmieKQuPbdkAK0c2/ssXaaHsWWOUHLxUBcew6D/6bD8erQOCHs9/2drutKs+bLpn5uSh3YukLjP+2w/DT+6wAELxwF9N0bAxN7f1qNyU+vAO65Frw4dnP6tvsR/BWPnGitrVbk81N/dksLhOXEdsmxD5NUuEFOKcPSTG93x5tuZsDkLSJtfV1orvpGcJQSGKYMEthhoXW543HLq6uRV+2kC6BIGGWnvupVNRX6dZKxh6KwJRnrGsCFvFafWiLv/+kELAqBdahvDldWRI/p4JkJW2zIqPzuC3DWBGsQ4utBa45ofOhS4nN8TecDr+DkdWONGsFptjH9TZWXwa9NzJxaSzOWOtE/x3qAI/6euvA69f+Y8pmrHZ9AR4ISG3OFQEXwHRB0pP2EwESZPncmaTMMWYhh3Tn+bbpBnt4/quKkeKrUi3BAxiH+SdD9cR0YsCCtgJuf7EaZAfjekFRLJviEzOgMwTSxnWnHe69Q==
  template:
    metadata:
      name: pihole-admin-secret
      namespace: pihole

