apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: "2025-04-10T01:46:48Z"
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: pihole-admin-secret
  namespace: pihole
  resourceVersion: "8189"
  uid: 54ddc0b3-f78a-4cb3-b8ef-f15d6e655d8a
spec:
  encryptedData:
    password: AgCVw0wiO3rNKfz0+jclgXj8zSxRRnLxTjOW5C4EIOeWrnownBz5SW8wegOKbYhxtZuXBCaBtB++he9pJysDQJlLv3VTYw2S1AHhyFVi2aQ/kOsjXtmTkMZZy6B/vBTtkkPLTwKC+gSsBlHH5BEsrnVAQTYaUBEwiJROPYLn+4ys//42P/kHhggJA/wXSUpaC7x1bYr/IDMQtFuIFK5iP75XqDJ1BAI3ZIv/jSEpLXoOum8mUMeHF7XQBi226U5P+cKKhb+izVQmJ3Zg2XVxyvNxJsoFyB4/rgkAfG7zq0exbBnnPDEi86oy/kmGyHqlixfFMHg2kZCE8RMgGf0DHP/Q14QsbJLKFLmqn3Xje/7Q2WbEALvEZ0eQVc4xA4HRtdMt7SgUms0zKe4yjVmyaeXX0kmfXIdSw10FmE3LpRJZ7B/2vXFeLD0PKNKXxqGO6OGqiMly1aAx2LcPQKfoKTsl/xi6Pff243VkBMgfKwMe4EJPdpRK8z3KsaZPusYFYO78+NEhxbTZE1QFTfx4Sl8c3KtRJ1xXTC983rxfrvQMsVqHIRVhlVBsH2iPbPhS6bF4s+gM8DlIZ+ozy6yCsz3+EB0J5T/F2hwOZR/F1vRskd3AYB4vN2+Q9D9ywb7bh5bB2xPt1DWDfLIdiIZyxUqkvOHWZdz2WSftksvZSQTWij8zo4VQk89+eH9d+Qh98O8zs2UzB2L4Zf5t4xBWMQ==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-admin-secret
      namespace: pihole
status:
  conditions:
  - lastTransitionTime: "2025-04-10T01:46:50Z"
    lastUpdateTime: "2025-04-10T01:46:50Z"
    status: "True"
    type: Synced
  observedGeneration: 1
