---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin-secret
  namespace: pihole
spec:
  encryptedData:
    password: AgBOwZfrtj2q6RUfuBQ5A253/veO1qRyujMK0A1I6J1xyehsKBrOcwcQfpqpf4gIhT/VzGWGinpnLVbx1PMokItbkT+sG63qfCUV9Hfa4Oj5Zmc/E09YQ2CijGU2aksVjly1edXmhVTLH+u4VaiQcxkVe9Uymbce5u5sSqwsi7/zq3xvmS6UzAFJQNW0ICqoY4npF/6Gm8TZrhtBc0Jign0rjP76YBRWiYU7NZ4xU9CwoopaF5b/3sd2AWcAnQNwXLVplHIrxk3HCNyIc09AqUh/fniyCCDdD+5VqaImTstArowyqUDthkfRNfRH47LjTmbmejMIBrQgVvWojSAgRc33wxKPYZO/2WoO5BrMF+VZg6prpZNhdYOrT39C4uVns22dftsS0ajegbvDQvqWWfVBsjBLBX8/aNGbSPVWao+tIlGMfN7uKDP8UR9RnIhCzCLr3pqp2K5jRFzBPIWUGPA6ra0Ej5pm1SenT+mnh4Zz+qNNZTBTGqexmkGFGpeWtZDJ7QhZycxMxw6GUCvrIg9oeCSkDnQNdudIykjH0w+j1TY4eq+BIroHPRADUTWSMDMqVcZxgfUxm2R0l4T38BaicQEA22xPBZVcSO6/RtcNzZtJMv0I4aUIg68KPtVN3S3Km+ad7LcD38D2n9Hggo/xtL8NHhor5y/iGVeuUfu17oakzg+KzsBSaNlSMzWTcK11mGDzvj7yBzTGkCpOJg==
  template:
    metadata:
      name: pihole-admin-secret
      namespace: pihole

