---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin-secret
  namespace: pihole
spec:
  encryptedData:
    password: AgAALiuo1sXiXdyMFF6lNzunKUuKnhJBpy4WHPOR2hE4Wdk8/e/4QzOEHalWZf8iijwRD2UhcnyoFN5jREQMh+bR7mWWbYrq1zJ5HJicNVvP86fb6HbrCEONRK/Q8F74mIXYhV3Hr+y9yRYiR0vDtYGYXsCbt9pSixfusUnMIqAidw7CnsrpqOyjsKU9zmUOlS18mZR9VBpbVwZjbpnjmKLrJ/gQrowGJ1iB81GlpaN+tKg9QhXYOGQznkjvRi+JtAVSmNK96z/X/SBw6VGxFkv/RZL/00bNXj9XIIwTYQYrdRlXIohcDgC6ge2qHf1IqYFBopipyUSIoaM13P7F0Uiycz5zz8QozUw4Vd1GikelOdQAr2Cl8xS8hhVsxiIraWG3PAUhl+ZcJLWtQxN2z58dYPSz6qku5sToR2bpkv712ZO1rzpRbJo7tdWhABOgo/y6Dhvgm5StlORJGYNtXicRSu+umzFzFIox7kg2Ut8f/XebMmJjj4QcEYsHwsMl0tJo358XH7od3cFwDhkQJXLB3N3OtGliJXesVov3y4iARtTMmfNjVm/YDGcKsFGrxFFC6Gi35qToqCdw8lfecQ7Ta2PYHbyK44RjfDJG0wXyRS4SwYiKKrw8oO50RFHzTma+i7nM5hwv2zvsUzuRv2pV6AuvmyaFOqB//jRruTaHdWfgQimGPGrmmI/lhwGNFlZD/UEBVUQwIUqeOVmc+Q==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-admin-secret
      namespace: pihole
