---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "nginx-ingress"
  namespace: "traefik"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nginx.thelemonsclan.com`)
      services:
        - kind: Service
          name: bitnami-nginx
          namespace: bitnami-nginx
          passHostHeader: true
          port: 443