apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: "2025-04-10T01:42:43Z"
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: longhorn-minio-credentials
  namespace: longhorn-system
  resourceVersion: "3961"
  uid: ece699fe-5922-4668-ba27-e256e6d6a931
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAyBQTNvLkRDLHfgI6NUPE40KPdcffmBpfaIUhwwoYkb2Y1vaWzAf6qP7PNSwK8Dp/pnuYYYSEBAEHLTuFUX2qaNTB5kIXw5ZmoHvCFMRhlkLYvY9pdtMA/QL0NnQ2aYhlT77upPlFe9uqI+AEBzRpIsiaenhPSJJ3I3BqaGJD5Hl86olGm5ha+A8bbob8QzOWhxcOUJug4rMq5tt3f1eqj1Qte2JDtqIvvmOcDLptp+MSfh3vW3jJuNcl/LYDAND37NsvvQ/T8tmxUHwz0+n9ka1ApWur5JVJ6czjtuSD+o2Q5yMcCmoIUCZ2ulsDA2bIy2i4vZ4Bxh2mYPnsvAgPZaR0mrYzDcVF6BkM4srJpd8SjQvpId79+WtzPeBdb0ifEf0jd9Su2alWYNdOYPHdKm5dgAuVC/Gij6lGsOqNaEP6wfvX7hM9b16GmGXFpJUPXESEqF3tixzx7FAgz52cYfnX6OggyXC1ZlB3QrFMwuSqEOl2c3x3BdBLifZi4k8p1YJYxTqIj4NBAeq0JUQM+GTXAYD2j8C9PkTJCshOIYfCQFBOTiMMnxxjEIiNNBdvYtrRGc73JquwV7bAKa5K/CJ0bxY7hdjL2NJDFvydtwqyzS6R04nO6BX7193iz6cl5uq+w+jetXzm57iCe+uceYypkjS43XzXktu/ikLunOLdNVfowavcTKms+mwX3l8qazaiaiOuuysBaCek/OKDeu8ITDA==
    AWS_ENDPOINTS: AgB2n+w9svXiZcqcsE6K+uFfexhqmYqkEFTM+eEFlwy2A3MKV/ACHMnoe74ImCY56fSxTMSo0fA0APVUlvGL/UJIoW/mR0Irk9fTumjvXa6t3yT3JUmbUe9rmJpffmlHTHXDFDfeKyeoYpmzA4fbvqG4oLjOdgX+RyRv8naOCjz4SHVPaM9+idSbEo4PQsVIIW+KoPBLf8BRfxQCfLS2iueNkLO1S6+Ig32BBTmfRa3+yVKhcpqaPxpZUEdjjpuw6yW6XsZ+nD9fZ3brhxf+EVv7zQRiPDegU7pJRZwE6BEPn2A4S18ciGDvn6rUiMTW9wOaDeolQ9oib4sVs5mSYg5rVkTujzBYxAZ1IWnOJN9+ZqQ8YvFEUiyYWbuxO5QYdyGqDLj1vwDGDKR6pilyJtbzWnA3ogcvwDCwvytHy94pV8jeg/Vpm2Tq7hpM1oDVptKXNy6/2vBhSyMLqgZhT+1vuf2Pah+lkW2tdpv7Hd0ryUs471GqsQEOYoikXjOzT1eNHOMp0xGCVyfTn9Nc4XeujycLiSKVlFsKyq38XToaMlpqfslgQTux8cGf0d1qCNoqkIuA5qW3+GyIY5VE/V7FQvgLa5LEds+v3x+hIbKzL2P7S93cQLODnFqbU2IVHuntrptRJhjO82eKSozUGo8Nv5il7zJJoXOzu8oUUYLljy6ykFvsXhzjRHDC+tiDuo5uY8uIaiR0dyzsWc7b3aXQRkhbUA2UuyA=
    AWS_SECRET_ACCESS_KEY: AgCThChxHuy1weC0eV1HrSLvQT1qy4ZyykRiat7LnovZWij//47kYxSjR5xuV9rT7xyZx5CFkdEGrvXPVmgULDVASuuRTzbnvU+wRu2fsM2a1e33d3Br+wlA/dL5KjLyN/DuhoJU+5v0UjSPrsA99oA/ht/5kQU+gPqdiyUcbEJTbK37j0BX4o219I4MTZbnRmZj9xpDvjQuQC8yT4m3kIFJBcSH+qMYna1KF+JSq/Xy8DVn8sMZiRgMhT9XZ2KxCqnTGxzvl/nl3VJtxJnIj9IbpxZKIjDSWF4q5U+g/rfejVoxtzmqmoKWRE1fK01R+svRkHwG8SAHhrUw8+zxJ1i3LQ5rLWyMx9qbjsbBGPkluChSEIrWGcDJy5C1yiULM/NIb8GdxnRqw9wecE0dpu7KHkYWXjpdeRQbm4YL+lFFZf86QAb4vo4oHfGjqxVJJ3FAXPEPlgy09BqjYYnKIEnpijZQFCfwdQBS//ua+4m+LiMBU6HGVNcsA+OTY5DEd84fk2j0sKmBZdUQwYj+mxj/QXMLd2csodaKEtV0iuzCgkOSx0F4F/D8U+yAcJeTyUyEeo4DAeu5mt/hbtTg32NOtKQWsv1GivKi1HHmK7p/l3zDKi3nlbfGFoeyR7tc69odSNEvB0ZQ5L4luzTvSK3a+RxX8+CJRxnY/zfuHhWDjdSRWh5y1Clj2MFXdZ6EvqAJVprHTglRUAPWeBTefGSepooHHsfv7ghNMl4WnZ36gbXz89pIDvJ4
  template:
    metadata:
      creationTimestamp: null
      name: longhorn-minio-credentials
      namespace: longhorn-system
    type: Opaque
status:
  conditions:
  - lastTransitionTime: "2025-04-10T01:42:43Z"
    lastUpdateTime: "2025-04-10T01:42:43Z"
    status: "True"
    type: Synced
  observedGeneration: 1
